services:
  db:
    image: mysql:latest
    container_name: mysql-notes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: notesapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: nest-notes-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      DATABASE_NAME: notesapp
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-notes-app
    restart: always
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend

volumes:
  mysql-data: